export const routes = [
  { key: 'about', label: { zh: '關於 FMT', en: 'About' } },
  { key: 'products', label: { zh: '產品平台', en: 'Products' } },
  { key: 'technologies', label: { zh: '核心技術', en: 'Technologies' } },
  { key: 'solutions', label: { zh: '解決方案', en: 'Solutions' } },
  { key: 'projects', label: { zh: '專案經驗', en: 'Projects' } },
  { key: 'news', label: { zh: '最新動態', en: 'News' } },
  { key: 'contact', label: { zh: '聯絡我們', en: 'Contact' } },
]

export const pageCopy = {
  zh: {
    common: {
      source: '內容依飛貓科技 2026 公司簡報、既有官方網站及公開軟體倉庫整理；產品配置與服務範圍以正式報價及專案確認為準。',
      updated: 'PUBLIC INFORMATION · UPDATED 2026.08',
      pending: '規格依專案確認',
      concept: 'AI 概念示意｜非實際交付畫面',
    },
    about: {
      eyebrow: 'ABOUT FEIMAO TECH', title: '跨越機構、控制與任務系統的工程團隊。',
      lead: '飛貓科技有限公司成立於 2021 年，專注於無人載具、機電整合、電子控制與智慧設備開發，提供從概念設計、原型驗證到系統整合與小量試產的一站式工程服務。',
      mission: '以 MIT 自主技術，打造可信賴、可重構的無人載具平台。',
      missionText: '我們把載具視為任務系統的一部分：依場域整合飛控、感測器、通訊、酬載、地面站與製造流程，縮短技術從構想到落地的距離。',
      capabilitiesTitle: '核心能力',
      capabilities: [
        ['機構與機電整合', '結構設計、治具與模具、3D 建模、BOM／SOP 與量產工程規劃。'],
        ['電子與控制系統', '嵌入式控制、GNSS／RF／CAN、感測與通訊、電源管理及任務控制整合。'],
        ['無人系統開發', '多旋翼、固定翼、VTOL、系留式平台、USV 與任務酬載整合。'],
        ['快速原型與製造', '3D 列印、複材與金屬加工、EPO 發泡成形、小量試產與品質檢核。'],
      ],
      qualificationsTitle: '資格與研發背景',
      qualifications: ['民航局無人機專業操作資格', '民航局無人機作業能力審查', '標檢局授權廠商資格', 'PTC 與 iPAS 3D 列印專業資格', 'FMT 商標註冊', '跨領域專案管理與無線電操作經驗'],
      timelineTitle: '公司歷程',
      timeline: [
        ['2021', '飛貓科技成立，建立 ArduPilot／PX4 與機電整合研發基礎。'],
        ['2022–23', '完成自主多旋翼平台、客製飛控與任務模組開發，擴展教育訓練。'],
        ['2024', '推出 ERIC 系列與影像模組，完成固定翼長航程飛行技術驗證。'],
        ['2025', '推進 C4950、4+1 VTOL、MIT 零組件、政府專案與產學合作。'],
        ['2026', '拓展國際展示、視覺導航、跨校研發與 FMTPlanner 地面導控軟體。'],
      ],
    },
    products: {
      eyebrow: 'PRODUCTS & PLATFORMS', title: '從飛行平台到導控軟體。',
      lead: '以模組化載具、MIT 零組件與任務軟體構成可延伸的產品組合。以下規格取自現有官方公開產品頁，實際配置依任務、法規與專案條件確認。',
      c4950Title: 'FMT C4950', c4950Lead: '折疊式 H4 多旋翼平台，可依需求整合運算、感測、通訊與任務酬載。',
      c4950Specs: [['構型', 'H4'], ['展開尺寸', '740 × 740 × 484 mm'], ['折疊尺寸', '450 × 410 × 484 mm'], ['軸距', '950 mm'], ['最大起飛重量', '10 kg'], ['公開頁面最大負載', '3,000 g'], ['電池', '6S 22,000 mAh'], ['公開頁面空載懸停實測', '50 min（非極限測試）']],
      aircraftTitle: '無人載具系列',
      aircraft: [
        ['ERIC P4', '四旋翼', '630 × 630 × 210 mm｜公開頁面空載懸停實測 43 min'],
        ['ERIC P6', '六旋翼', '670 × 730 × 210 mm｜公開頁面空載懸停實測 45 min'],
        ['Cheirotonus V1', '多用途四旋翼', '800 mm 軸距｜公開頁面空載懸停實測 30 min'],
        ['Q4980', '重載四旋翼', '物流、研發與載重任務整合平台'],
        ['FMT P6', '大型六旋翼', '大型載具與任務酬載整合平台'],
        ['Batwing', '固定翼平台', '飛行載具與任務系統配置依專案確認'],
      ],
      componentsTitle: 'MIT 零組件與製造',
      components: [
        ['FMT F5043', '5 吋螺旋槳', '台灣設計與製造，支援模具開發、量產導入與品質檢核。'],
        ['訓練輔助器材', '三軸／四軸訓練架', '協助操作訓練、裝調與安全流程建立。'],
        ['快速製造', '原型與小量試產', '3D 列印、複材、金屬加工、EPO 發泡成形及客製治具。'],
      ],
      plannerTitle: 'FMTPlanner V1.1.2', plannerLead: '以 ArduPilot Mission Planner 為基礎製作的 FMT 客製化地面站，針對台灣任務規劃、繁體中文操作與多構型載具整合。',
      plannerFeatures: ['多旋翼、固定翼、VTOL、車／船與潛航器構型辨識', 'AUTO 任務狀態、Mission Item、距離、進度與 ETA', '台灣限禁航區圖層與完整起飛／航段／返航路徑檢查', '高度與地形剖面、地形淨空及一般高度基準提示', 'GPS／RTK 狀態、QNH、空速計歸零與飛行前檢查入口', '繁體中文遙測、參數保護及本機去識別化錯誤回報'],
      plannerCaution: '高度與空域檢查屬任務規劃輔助，不構成飛行許可或法律判定；正式作業仍須確認最新法規、NOTAM、天候與設備狀態。',
      github: '查看公開原始碼與版本',
    },
    technologies: {
      eyebrow: 'ENGINEERING CAPABILITIES', title: '把跨領域技術整合成可執行的系統。',
      lead: 'FMT 的核心不在單一零件，而在載具、飛控、感測、通訊、軟體與製造之間的工程整合。',
      pillars: [
        ['01', 'Flight Platform', '飛行平台工程', '多旋翼、固定翼、VTOL 與系留式載具的結構、動力、重量與任務配置。', ['結構設計', '動力系統', '載具調校', '任務酬載']],
        ['02', 'Avionics & Control', '航電與控制', 'ArduPilot／PX4 飛控整合、嵌入式控制、感測器與通訊介面。', ['MAVLink', 'GNSS／RTK', 'RF／CAN', '參數調校']],
        ['03', 'Navigation & Perception', '導航與感知', '視覺、LiDAR、AI 邊緣運算與 GPS-denied 任務模組的整合驗證。', ['Vision', 'LiDAR', 'AI Edge', 'Sensor Fusion']],
        ['04', 'Mission Software', '任務與導控軟體', '地面站、遙測介面、航線規劃、空域與地形檢查及任務狀態呈現。', ['FMTPlanner', 'Airspace', 'Terrain', 'Telemetry']],
        ['05', 'Rapid Manufacturing', '快速製造', '從 CAD、3D 列印與模具到複材、EPO 與小量試產的快速迭代。', ['CAD', 'Additive', 'EPO', 'BOM／SOP']],
        ['06', 'System Validation', '系統驗證', '以原型、SITL、現地測試及交付流程驗證軟硬體整合結果。', ['POC', 'SITL', 'Field Test', 'QA']],
      ],
      processTitle: '工程流程', process: [['01', '需求與場域'], ['02', '系統架構'], ['03', '原型與整合'], ['04', '測試與迭代'], ['05', '交付與維護']],
    },
    solutions: {
      eyebrow: 'MISSION SOLUTIONS', title: '以任務需求定義平台。',
      lead: '依場域、法規、環境與資料需求配置載具、酬載、通訊與操作流程。每項方案均須經正式需求訪談與工程評估。',
      items: [
        ['國防與安全訓練', '訓練載具、模擬器、操作與維修課程、任務平台及在地供應鏈整合。', ['訓練平台', '模擬器', '操作課程', '維保流程']],
        ['巡檢與災害防救', '道路、邊坡、河川與災區的影像巡查、地形資料與任務規劃。', ['道路巡查', '邊坡監測', '搜救支援', '物資投放']],
        ['測繪與智慧感知', '正射影像、點雲、AI 辨識、Vision／LiDAR 與邊緣運算整合。', ['Mapping', 'Point Cloud', 'AI Vision', 'LiDAR']],
        ['教育與研究', '無人機操作、組裝、飛控、3D 列印與跨校研發計畫技術支援。', ['專題支援', '飛控調校', '實作課程', '研究驗證']],
        ['客製無人系統', 'UAV、USV、地面站、充電塔 POC 與特殊任務機電系統整合。', ['UAV', 'USV', 'Ground Station', 'POC']],
        ['空拍與工程紀錄', '長航程、活動、工程與環境紀錄之任務規劃、合法申請與影像交付。', ['空域申請', '航線規劃', '工程影像', '資料交付']],
      ],
    },
    projects: {
      eyebrow: 'SELECTED EXPERIENCE', title: '從研究驗證到公開展示。',
      lead: '以下內容整理自公司提供的 2026 簡報，僅呈現已授權公開的高階專案摘要，不揭露任務位置、敏感配置或未公開客戶資料。',
      cases: [
        ['2026', '總統盃無人機挑戰賽', '與國防大學、律芯科技及中科院航空所組成聯隊並進入決賽；FMT 提供載具平台與系統整合。', 'project-flight-demo.webp'],
        ['2026', 'AIxVNAV 視覺導航展示', '以 FMT UAV 平台整合 Vantor 視覺導航模組，在展示任務中完成 GPS-denied 環境下 2 km 自主飛行。', 'project-vantor.webp'],
        ['2026', 'Japan Drone 聯合參展', '與台灣無人系統夥伴於東京 Japan Drone 2026 台灣館聯合展示。', null],
        ['2026', '國科會跨校無人機計畫', '支援清華大學領軍的五校研究團隊，提供大型多旋翼、飛控調校、任務規劃與現地測試。', null],
        ['2026', '宜蘭大學 USV 產學合作', '共同進行無人船結構、機電、控制載板、現地下水測試與學生實作。', 'project-usv.webp'],
        ['2024–25', '長航程與空拍任務', '執行跨海長航程驗證、道路防災巡查、工程紀錄與活動影像等公開任務。', 'project-gorge.webp'],
      ],
      serviceTitle: '政府與工程履約經驗', serviceText: '包含無人機模擬器軟硬體整合、移動式地面站工程紀錄、訓練平台、任務載具、空拍與技術文件等。詳細範圍依個別公開授權與契約保密條款提供。',
    },
    news: {
      eyebrow: 'NEWS & MILESTONES', title: '研發、合作與產品進展。',
      lead: '此頁先以已確認的重要里程碑建立內容架構；後續可接續新增正式新聞稿、活動照片與媒體連結。',
      items: [
        ['2026.08', 'FMTPlanner V1.1.2 發布', '完成 AUTO 任務狀態列、飛行前檢查、RTK 入口、嵌入式 3D 地圖及多項繁體中文、效能與穩定性修正。', 'SOFTWARE'],
        ['2026', '總統盃無人機挑戰賽合作', '多支產學研聯隊採用或整合 FMT 無人機平台，其中國防大學聯隊晉級決賽。', 'COLLABORATION'],
        ['2026', 'Japan Drone 東京聯合參展', '與台灣產業夥伴共同參與國際無人機展，呈現台灣無人系統整合能力。', 'EXHIBITION'],
        ['2026', 'AIxVNAV 視覺導航展示', '參與漢翔與 Vantor 技術展示，完成飛行平台與視覺導航模組整合。', 'FLIGHT TEST'],
        ['2025', '品牌與量產能力推進', 'FMT 商標核准、MIT 零組件與 C4950 平台開發，並持續政府及產學專案。', 'MILESTONE'],
        ['2024', '固定翼長航程技術驗證', '完成固定翼跨海飛行任務，驗證航線規劃、通訊與飛行整合流程。', 'VALIDATION'],
      ],
    },
    contact: {
      eyebrow: 'CONTACT FMT', title: '把任務需求轉成工程路徑。',
      lead: '請提供場域、任務目標、載具構型、酬載、通訊、時程與法規條件；FMT 將依可行性與資訊公開範圍進行初步討論。',
      primary: '專案與商務聯絡', support: '一般服務聯絡', location: '服務地區', locationValue: 'Taiwan · 台灣', website: '官方網站', repository: 'FMTPlanner 公開倉庫',
      checklistTitle: '建議提供資訊', checklist: ['任務場域與操作環境', '預期載具與任務時間', '酬載、感測與資料需求', '通訊距離與操作方式', '預計時程及交付形式', '可公開與保密資訊界線'],
      mailAction: '寄送需求摘要',
    },
  },
  en: {
    common: {
      source: 'Content is compiled from FMT’s 2026 company deck, its existing public website, and the public FMTPlanner repository. Final configurations and scope remain subject to project confirmation.',
      updated: 'PUBLIC INFORMATION · UPDATED 2026.08', pending: 'Configuration by project', concept: 'AI CONCEPT VISUAL · NOT A DELIVERED SYSTEM',
    },
    about: {
      eyebrow: 'ABOUT FEIMAO TECH', title: 'Engineering across mechanics, controls, and mission systems.',
      lead: 'Founded in 2021, FeiMao Tech develops unmanned systems, mechatronics, electronic controls, and intelligent equipment—from concept and prototype to integration and low-volume production.',
      mission: 'Build dependable, reconfigurable unmanned platforms with Taiwan-developed technology.',
      missionText: 'We treat the aircraft as one part of a mission system, integrating flight control, sensing, communications, payloads, ground control, and manufacturing around the operating environment.',
      capabilitiesTitle: 'Core capabilities',
      capabilities: [['Mechanical integration', 'Structures, fixtures, molds, 3D modeling, BOM/SOP, and production engineering.'], ['Electronics & controls', 'Embedded control, GNSS/RF/CAN, sensing, communications, power, and mission controls.'], ['Unmanned systems', 'Multirotor, fixed-wing, VTOL, tethered platforms, USVs, and payload integration.'], ['Rapid manufacturing', 'Additive manufacturing, composites, metals, EPO molding, low-volume production, and QA.']],
      qualificationsTitle: 'Qualifications & R&D background', qualifications: ['CAA professional UAV operator qualifications', 'CAA UAV operations capability review', 'BSMI-authorized supplier qualification', 'PTC and iPAS additive-manufacturing credentials', 'Registered FMT trademark', 'Cross-disciplinary project and radio-operation experience'],
      timelineTitle: 'Company timeline', timeline: [['2021', 'FMT founded; established ArduPilot/PX4 and mechatronics foundations.'], ['2022–23', 'Developed multirotor platforms, custom flight controls, payload modules, and training.'], ['2024', 'Introduced ERIC platforms and imaging modules; validated long-range fixed-wing workflows.'], ['2025', 'Advanced C4950, 4+1 VTOL, MIT components, public-sector projects, and academic work.'], ['2026', 'Expanded international showcases, visual navigation, research programs, and FMTPlanner.']],
    },
    products: {
      eyebrow: 'PRODUCTS & PLATFORMS', title: 'From flight platforms to mission-control software.',
      lead: 'A modular portfolio of vehicles, Taiwan-made components, and mission software. Specifications below come from the current public product page; final configuration depends on mission, regulation, and project conditions.',
      c4950Title: 'FMT C4950', c4950Lead: 'A foldable H4 multirotor platform configurable for compute, sensing, communications, and mission payloads.',
      c4950Specs: [['Frame', 'H4'], ['Expanded', '740 × 740 × 484 mm'], ['Folded', '450 × 410 × 484 mm'], ['Wheelbase', '950 mm'], ['Maximum takeoff weight', '10 kg'], ['Published maximum payload', '3,000 g'], ['Battery', '6S 22,000 mAh'], ['Published no-load hover test', '50 min (non-limit test)']],
      aircraftTitle: 'Unmanned vehicle series', aircraft: [['ERIC P4', 'Quadrotor', '630 × 630 × 210 mm | published no-load hover test: 43 min'], ['ERIC P6', 'Hexarotor', '670 × 730 × 210 mm | published no-load hover test: 45 min'], ['Cheirotonus V1', 'Multipurpose quadrotor', '800 mm wheelbase | published no-load hover test: 30 min'], ['Q4980', 'Heavy-lift quadrotor', 'Platform for logistics, R&D, and payload integration'], ['FMT P6', 'Large hexarotor', 'Large-vehicle and mission-payload integration platform'], ['Batwing', 'Fixed-wing platform', 'Aircraft and mission configuration confirmed per project']],
      componentsTitle: 'MIT components & manufacturing', components: [['FMT F5043', '5-inch propeller', 'Designed and manufactured in Taiwan with mold, production, and QA support.'], ['Training aids', 'Three-/four-axis training frames', 'Supports operation training, setup, and safety procedures.'], ['Rapid manufacturing', 'Prototypes & pilot production', '3D printing, composites, metals, EPO molding, and custom fixtures.']],
      plannerTitle: 'FMTPlanner V1.1.2', plannerLead: 'FMT’s customized ground-control station based on ArduPilot Mission Planner, focused on Taiwan mission planning, Traditional Chinese operations, and multi-vehicle integration.',
      plannerFeatures: ['Vehicle-aware modes for multirotor, fixed-wing, VTOL, rover/boat, and sub', 'AUTO mission state, Mission Item, distance, progress, and ETA', 'Taiwan airspace overlays and takeoff/mission/return route checks', 'Altitude and terrain profile with advisory clearance warnings', 'GPS/RTK state, QNH, airspeed-zero, and preflight access', 'Traditional Chinese telemetry, protected parameters, and local privacy-safe issue reporting'],
      plannerCaution: 'Altitude and airspace checks are planning aids—not flight permission or legal determinations. Operators must verify current regulation, NOTAM, weather, and aircraft condition.', github: 'View public source and releases',
    },
    technologies: {
      eyebrow: 'ENGINEERING CAPABILITIES', title: 'Turning cross-domain technology into deployable systems.', lead: 'FMT’s core capability is integration across aircraft, flight control, sensing, communications, software, and manufacturing.',
      pillars: [['01', 'Flight Platform', 'Aircraft engineering', 'Structures, propulsion, weight, and mission configuration for multirotor, fixed-wing, VTOL, and tethered systems.', ['Structures', 'Propulsion', 'Tuning', 'Payloads']], ['02', 'Avionics & Control', 'Avionics and control', 'ArduPilot/PX4, embedded control, sensing, and communications interfaces.', ['MAVLink', 'GNSS/RTK', 'RF/CAN', 'Parameters']], ['03', 'Navigation & Perception', 'Navigation and perception', 'Integration of vision, LiDAR, AI edge compute, and GPS-denied mission modules.', ['Vision', 'LiDAR', 'AI Edge', 'Sensor Fusion']], ['04', 'Mission Software', 'Mission software', 'Ground control, telemetry, route planning, airspace/terrain checks, and mission status.', ['FMTPlanner', 'Airspace', 'Terrain', 'Telemetry']], ['05', 'Rapid Manufacturing', 'Rapid manufacturing', 'Fast iteration from CAD and additive manufacturing to molds, composites, EPO, and pilot builds.', ['CAD', 'Additive', 'EPO', 'BOM/SOP']], ['06', 'System Validation', 'System validation', 'Prototype, SITL, field testing, and delivery workflows for integrated systems.', ['POC', 'SITL', 'Field Test', 'QA']]],
      processTitle: 'Engineering process', process: [['01', 'Mission context'], ['02', 'System architecture'], ['03', 'Prototype & integrate'], ['04', 'Test & iterate'], ['05', 'Deliver & support']],
    },
    solutions: {
      eyebrow: 'MISSION SOLUTIONS', title: 'Define the platform around the mission.', lead: 'Aircraft, payloads, communications, and procedures are configured around environment, regulation, and data needs. Every engagement begins with formal requirements and feasibility review.',
      items: [['Defense & security training', 'Training aircraft, simulators, operations and maintenance courses, mission platforms, and local supply-chain integration.', ['Training aircraft', 'Simulation', 'Courses', 'Maintenance']], ['Inspection & disaster response', 'Imaging, terrain data, and mission planning for roads, slopes, rivers, and affected areas.', ['Roads', 'Slopes', 'Search & rescue', 'Delivery']], ['Mapping & intelligent sensing', 'Orthomosaics, point clouds, AI recognition, vision/LiDAR, and edge compute.', ['Mapping', 'Point Cloud', 'AI Vision', 'LiDAR']], ['Education & research', 'UAV operations, assembly, flight controls, additive manufacturing, and research support.', ['Projects', 'Tuning', 'Courses', 'Validation']], ['Custom unmanned systems', 'UAVs, USVs, ground stations, charging-tower POCs, and special-purpose mechatronics.', ['UAV', 'USV', 'Ground Station', 'POC']], ['Aerial imaging & engineering records', 'Airspace coordination, flight planning, engineering documentation, and media delivery.', ['Airspace', 'Route planning', 'Engineering media', 'Delivery']]],
    },
    projects: {
      eyebrow: 'SELECTED EXPERIENCE', title: 'From research validation to public demonstrations.', lead: 'The following high-level summaries are drawn from FMT’s supplied 2026 company deck. Sensitive configurations, mission locations, and non-public customer information are intentionally omitted.',
      cases: [['2026', 'Presidential Drone Challenge', 'A consortium with National Defense University, an industry technology partner, and NCSIST Aeronautical Systems advanced to the final; FMT provided platform and system integration.', 'project-flight-demo.webp'], ['2026', 'AIxVNAV visual-navigation demo', 'An FMT UAV integrated a Vantor visual-navigation module and completed a 2 km autonomous demonstration in a GPS-denied environment.', 'project-vantor.webp'], ['2026', 'Japan Drone joint exhibition', 'Joined Taiwan unmanned-system partners at the Japan Drone 2026 Taiwan Pavilion in Tokyo.', null], ['2026', 'NSTC multi-university program', 'Supported an NTHU-led five-university team with large multirotor integration, tuning, mission planning, and field testing.', null], ['2026', 'NIU USV collaboration', 'Joint work on USV structures, mechatronics, controls, water testing, and student practice.', 'project-usv.webp'], ['2024–25', 'Long-range and aerial missions', 'Public work included over-water validation, road-disaster inspection, engineering records, and event imaging.', 'project-gorge.webp']],
      serviceTitle: 'Public-sector & engineering delivery', serviceText: 'Experience includes UAV simulator integration, mobile ground-station engineering documentation, training platforms, mission vehicles, aerial imaging, and technical records. Details remain subject to publication approvals and confidentiality terms.',
    },
    news: {
      eyebrow: 'NEWS & MILESTONES', title: 'R&D, partnerships, and product progress.', lead: 'This initial news structure is populated with verified milestones and can later expand with formal releases, galleries, and media links.',
      items: [['2026.08', 'FMTPlanner V1.1.2 released', 'Added the rebuilt AUTO mission panel, preflight access, RTK entry, embedded 3D map, Traditional Chinese updates, and stability improvements.', 'SOFTWARE'], ['2026', 'Presidential Drone Challenge collaboration', 'Multiple academic and industry teams adopted or integrated FMT platforms; the NDU consortium advanced to the final.', 'COLLABORATION'], ['2026', 'Japan Drone Tokyo joint exhibition', 'FMT joined Taiwan industry partners to present unmanned-system integration capabilities.', 'EXHIBITION'], ['2026', 'AIxVNAV visual-navigation demo', 'Participated in an AIDC/Vantor demonstration integrating an FMT platform and visual navigation.', 'FLIGHT TEST'], ['2025', 'Brand and production capabilities', 'Advanced the FMT trademark, MIT components, C4950 platform, and public-sector and academic programs.', 'MILESTONE'], ['2024', 'Fixed-wing long-range validation', 'Completed an over-water fixed-wing mission to validate planning, communications, and flight workflows.', 'VALIDATION']],
    },
    contact: {
      eyebrow: 'CONTACT FMT', title: 'Turn mission needs into an engineering path.', lead: 'Share the operating environment, mission goal, vehicle, payload, communications, schedule, and regulatory context. FMT will begin with feasibility and publication-scope review.',
      primary: 'Projects & business', support: 'General service', location: 'Service region', locationValue: 'Taiwan', website: 'Official website', repository: 'FMTPlanner public repository', checklistTitle: 'Useful information to include', checklist: ['Mission location and environment', 'Expected aircraft and duration', 'Payload, sensing, and data needs', 'Communications range and operating model', 'Schedule and delivery format', 'Public vs. confidential boundaries'], mailAction: 'Send requirements summary',
    },
  },
}
